exclude:
  - node_modules
  - script

sass:
  style: :compressed

theme: jekyll-theme-primer

github:
  private: false
  license:
    name: MIT
  source:
    branch: "master"
    path: "/"
  repository_url: "https://github.com/pages-themes/primer"
  
title: "Quantization and Disentanglement: Neural Speech Reconstruction from Brain Activity"
#description: Primer is a Jekyll theme for GitHub Pages

baseurl: "/QuantDisBrain"
url: "https://neurofusex.github.io"
